### ISSUE TITLE
Provide the Senzing entity ID in the POST response

### ISSUE THREAD

**Issue by ZackHill05** [Senzing/senzing-api-server#121]
**Is your feature request related to a problem? Please describe.**
Kinda. If posting to the Senzing API “/data-sources/{dataSourceCode}/records” will continue to only take one record in the request body, it's tedious to then have to make a GET call to “/data-sources/{dataSourceCode}/records/{recordID}” to get the Senzing Entity ID. 

**Describe the solution you'd like**
Why not provide the Senzing Entity ID in the response of the POST call?

**Describe alternatives you've considered**
Alternative is the separate GET call. I am not advocating deprecating the GET call with providing  the Senzing Entity ID in the POST call, I'm asking why aren't you providing the Senzing Entity ID in the response.

**Additional context**

**Comment by barrycaceres** [comment]
There is a potential race condition here.... if loading a large number of records concurrently, the entity ID could be outdated by the time you get it back.

It is best to query entities by their record ID if you want consistency.  But I can still look at returning it.  However, I don't think the native Senzing API provides it on addRecord() calls

**Comment by barrycaceres** [comment]
The relevant call might be to lookup entities by the visitor record ID.

GET /data-sources/{dataSourceCode}/records/{recordId}/entity

This ensures that you are not using an entity ID that the "record of interest" is no longer a part of due to unresolved/re-resolve processing.  That is to say that entity ID's are transient.

There is however a way to get "info" in "all affected entities" and I could add the return the of entity ID for the record as well as an enhancement -- both would increase overhead.  The "get info" is going to be an optional flag that increases overhead but won't tell you specifically which entity ID your record belongs to.... the other way would be for me to call the native function to get the entity ID for a record before retuning from the POST.

But again, I am afraid we are going down the path of what is not a best practice since entity ID's are transient.

Let me know if this all makes sense.

**Comment by barrycaceres** [comment]
@ZackHill05 -- just checking in to see if you have an answer to my question above.  I can add an optional parameter to return the entity ID so the performance hit is not always incurred unless you want it the information back.  I believe that is the route I would go with this.  The "info" options would not tell me the exact entity ID for the loaded record, but rather which entity IDs were affected by the load, so one of N entity IDs in the info is the one you just loaded.
