### ISSUE TITLE
How to get 3rd level and 4th level relationship information from the Senzing API?

### ISSUE THREAD

**Issue by SaravananKalimuthu21** [Senzing/senzing-api-server#147]
Hi Team,

We are using this (**/entity-networks**) API (Ref: http://editor.swagger.io/?url=https://raw.githubusercontent.com/Senzing/senzing-rest-api/master/senzing-rest-api.yaml) to retrieve data from the database to reflect the data in our graph. 

We are getting resolveEntity and relatedEntities with a parent information and a single level child information.

![api_result](https://user-images.githubusercontent.com/48215082/79192803-0a5f0a80-7e47-11ea-8972-90aa8983edcb.png)

How can we get more level of information. i.e, A parent level information with a child level information and a child of child level information and so on.

Can you people help us and resolve this query?

Thanks.

**Comment by SaravananKalimuthu21** [comment]
Also we need the relevant information for all the attribute in the relatedEntities array. Then only we are able to utilize the proper information.

![relatedEntities](https://user-images.githubusercontent.com/48215082/79305170-7c4f5680-7f10-11ea-9fcb-f023747bc741.png)

**Comment by barrycaceres** [comment]
The way to do this with the `GET /entity-networks` API is to set the `buildOut` parameter to `2` or `3` (for first-degree or second-degree relationships, respectively).

If set to `2` then you will get full data for the first-degree related entities partial data for the second-degree related entities.

If set to `3` then you will get full data for the first-degree and second-degree related entities and partial data for the third-degree related entities.

The "partial" data at the edge of the graph is typically so an icon can be rendered to indicate that the relationships can be expanded further (thus requiring another query centered on the target entity being expanded).

The `buildOut` query parameter is documented in the REST API specification.

Please close this issue if this answers your question.

**Comment by SaravananKalimuthu21** [comment]
Hi Barry,

We tried the above suggestion but it didn't help us resolving the issue.

We set the **buildOut** param value to **2** (default value was 1). The API kept on trying to retrieve the data but it ended up with timed out message (couldn't get the data).

The performance was too poor it used to take more than 5 mins and got no results.

![1](https://user-images.githubusercontent.com/48215082/79420235-26dd7d00-7fd6-11ea-86ec-8647354726a8.png)

Used params: **maxDegrees**=1, **buildOut**=2, **maxEntities**=40, **withRaw**=true
Do we need to change anyother params to get this done?

Is there any other way to extend the relationship information? or any other API for this?

Thanks.

**Comment by barrycaceres** [comment]
**First off, the entity-network call should not hang like that so there is a problem we need to investigate there.  Let me ask you a few questions regarding that....**

1) Is there an error produced by the API server when it times out?  I need to rule that out.

2) Does one of the entities being requested have a very large number of relationships or records?

**Secondly, let me try to explain things in a more thorough manner regarding the parameters:**

1) You specify the entities in your network with the `e` or `entities` parameters either as record IDs with data sources or entity IDs.

2) The network is generated by first trying to find paths between the entities you specified of at most `maxDegrees`.  So if you specified entities `1000` and `2000` and `maxDegrees=2`  and entities `1000` and `2000` were connected by entity `1500` then your network would include `1000`, `2000` and `1500` and you would get `RESOLVED_ENTITY` values for all 3 of those entities.  But you would ALSO get `RELATED_ENTITIES` values for entity `1500` when examining the entity data returned for `1000` and `2000`.  So to get the complete data for `1500` you would want to look at the `RESOLVED_ENTITY` value.

3) After the network is generated, we go back to original specified entities and "build out" from them at `buildOut` degrees.  For the example above, we will NOT build out on entity `1500` since it was not in the list of specified entities.  If we had specified `buildOut=1` then we would find ALL one-degree related entities for `1000` and `2000` and return them as well (this happens to include `1500` but may include other entities).  If `buildOut=2` was specified then we would also expand the 1-degree relationships of `1500` because we are effectively building it out at 1 degree to achieve 2 degrees on its neighbors.  Suppose entity `1000` is also related to entity `500` and entity `2000` is also related to entity `2500` and `buildOut=1` was specified.  This would mean that we would ALSO get `RESOLVED_ENTITY` values for `500` and `2500` -- or in total we would get "entity data" (aka: `SzEntityData`) with a `RESOLVED_ENTITY`(aka: `SzResolvedEntity`) for `500`, `1000`, `1500`, `2000` and `2500`.  

4) This "build out" phase is limited by the `maxEntities` parameter.   So take the previous example where we returned entity data for `500`, `1000`, `1500`, `2000` and `2500` and imagine we specified `maxEntities=4`.  With that `maxEntities=4` setting either `500` or `2500` would be *excluded* from the results depending on which was reached first in the build out.  We do not guarantee an ordering for the build out.

The trick to finding the complete data for your related entities might look like this:

1) Iterate over all returned `SzEntityData` ("Entity Data") objects.  Place them all in a lookup table using the `resolvedEntity.entityId` (`RESOLVED_ENTITY.ENTITY_ID`) as the lookup key.

2) When iterating over the related entities (aka: "`SzEntityData.relatedEntities`or `RELATED_ENTITIES`) check the lookup table created in (1) to see if the complete data exists as a "resolved entity".

3) If you come across a "related entity" for which there is no "resolved entity" then you either excluded it via `maxEntities` OR it is at the edge of the graph and needs to be obtained with a second API call to `GET /entities/{entityId}`.

NOTE `GET /entities/{entityId}` has a special parameter called `withRelated`.  If specified, the call to retrieve the entity is actually a call to get the network of that single entity with a `buildOut` value `1` and a `maxEntities` value of `1000` (i.e.: to get up to 1000 related entities in their entirety).

I hope this clarifies things a bit and let's try to diagnose why it is taking forever to return.

**Comment by barrycaceres** [comment]
Just as a follow-up, this is our Java function for implementing `GET /entities/{entity}` that shows how we augment the related entities:

```
  private static SzEntityData getAugmentedEntityData(
      long                    entityId,
      Map<Long, SzEntityData> dataMap,
      SzApiProvider             provider)
  {
    // get the result entity data
    SzEntityData entityData = dataMap.get(entityId);

    // check if we can augment the related entities that were found
    // so they are not partial responses since they are part of the
    // entity network build-out
    List<SzRelatedEntity> relatedEntities
        = entityData.getRelatedEntities();

    // loop over the related entities
    for (SzRelatedEntity relatedEntity : relatedEntities) {
      // get the related entity data (should be present)
      SzEntityData relatedData = dataMap.get(relatedEntity.getEntityId());

      // just in case not present because of entity count limits
      if (relatedData == null) continue;

      // get the resolved entity for the related entity
      SzResolvedEntity related = relatedData.getResolvedEntity();

      // get the features and records
      Map<String, List<SzEntityFeature>> features
          = related.getFeatures();

      List<SzMatchedRecord> records = related.getRecords();

      // summarize the records
      List<SzDataSourceRecordSummary> summaries
          = SzResolvedEntity.summarizeRecords(records);

      // set the features and "data" fields
      relatedEntity.setFeatures(
          features, (f) -> provider.getAttributeClassForFeature(f));

      // set the records and record summaries
      relatedEntity.setRecords(records);
      relatedEntity.setRecordSummaries(summaries);
      relatedEntity.setPartial(false);
    }

    return entityData;
  }


```

**Comment by barrycaceres** [comment]
NOTE: if we were to fully populate every "related entity" we return you could end up with megabytes of redundant JSON for highly related entities.  That is why the full information is kept at the "resolved entity" and should be looked up.  We fudge this for a single entity retrieval if `withRelated=true` since we are not going to end up multiplying the response size exponentially for only a single entity.  This is why `SzRelatedEntity.partial` property exists -- to tell you when the data is partial and you have to either lookup the additional info from the `SzResolvedEntity` or do another `GET` operation to retrieve it.

**Comment by SaravananKalimuthu21** [comment]
1. Is there an error produced by the API server when it times out? I need to rule that out.
**We didn't get any error message from the API server other than "Failed to load response data"**
2. Does one of the entities being requested have a very large number of relationships or records?
**yeah it may have large information/records.**
3. Which version of the API Server and which version of Senzing product are you using?
**Senzing version: 1.14.6**

So what you are saying is, In order to get the details of records inside the relatedEntities{} we have to loop through it and make separate api calls with its entityId right?

**Comment by barrycaceres** [comment]
I believe you have stumbled across a bug in version `1.14.6` of the Senzing software if we are not getting completion from the entity networks API call.

The defacto answer is "try again using version 1.14.7", but I checked and to our knowledge there were no fixes between version 1.14.6 and 1.14.7 that would correct this kind of problem.

Can you open a ZenDesk ticket and we can go from there and setup a zoom call and try to diagnose it with you on a screen share?

**Comment by SaravananKalimuthu21** [comment]
1. What operating system is this running under and is it within Docker?
**It it running in CentOS 7 and yes it is within docker.**
2. Do you see a core file on the file system where the API server is running?
**No we can't see such core files in the server where the API is running.**
3. Do you see a Java heap or stack dump file on the file system where the API server is running?
**No.**

Can you open a ZenDesk ticket and we can go from there and setup a zoom call and try to diagnose it with you on a screen share?
**Sure.**

**Comment by SaravananKalimuthu21** [comment]
Hi Barry,

Created a zendesk ticket. Here is the link. 
https://senzing.zendesk.com/hc/en-us/requests/2526

May i know which timezone are you in?

**Comment by SaravananKalimuthu21** [comment]
Barry,

Are you ready for a call?

**Comment by barrycaceres** [comment]
Senzing 1.15.2 fixes the performance bug for the entity network call and should fix this.  Can you confirm and close this issue?

**Comment by SaravananKalimuthu21** [comment]
Hey sorry for the delay,

We'll check that and let you know, Barry.

**Comment by SaravananKalimuthu21** [comment]
Barry,

We are presently on the Senzing API Version 1.14.6

How to upgrade it to 1.15.2? 

We got this documentation https://senzing.zendesk.com/hc/en-us/articles/360047138333-Updating-the-Senzing-API-configuration-from-1-14-x-to-1-15 

Is that right?

If yes, We don't have this file in our server **/opt/senzing/g2/resources/config/g2core-config-upgrade-1.14-to-1.15.gtc**, also it seems to have some upgrage on DB schema.

Can you help us upgrading the Senzing version and DB Schema?

**Comment by SaravananKalimuthu21** [comment]
Hi Barry,

We did upgrade the Senzing version to the latest 1.15.3

Now we are able to see the results for **Ajisen china holdings limited** we used for testing.

We will try to get the 3rd level and 4th level data further with a separate API calls as you suggested.

I'll close the issue here. Thanks for the help..!
