### ISSUE TITLE
Creating standard releases (option in GitHub)to keep up with Senzing builds 

### ISSUE THREAD

**Issue by NilayBhatt** [Senzing/senzing-api-server#163]
**Is your feature request related to a problem? Please describe.**
Creating standard releases to keep up with Senzing builds for easier versioning of the API and features being released. This can help users easily figure out what version of the API is compatible with a given G2 version being used.
**Describe the solution you'd like**
A shippable release package with notes of features and usage using the github tags

**Comment by barrycaceres** [comment]
Currently the API Server is disconnected from the product itself.  A single version of the API server usually supports a range of versions of the product (depending on which native API methods are required to implement the operations in the API Server).  Because of this, the API Server often releases more frequently than the product so we can keep up with customer requests and expand the functionality.  Sometimes, when large overhauls are required, it may release less often than the Senzing product.  We discuss "productizing" the API server, but so far we have avoided that so we can remain flexible.

**Comment by NilayBhatt** [comment]
I see why that is the case, but using releases with the right tags (of supported versions/features) will greatly aid consumers of this code. Something like even using Actions to publish a fat jar with a little readme of what versions of G2 it supports will be a great feature and easier for consumers to plug and play right away, without cloning the whole repo and all the version history.

**Comment by docktermj** [comment]
@NilayBhatt  When you say "tags",  are you referring to a feature of GitHub (i.e. "Labels") or are you referring to information in [CHANGELOG.md](https://github.com/Senzing/senzing-api-server/blob/master/CHANGELOG.md) that would be helpful, or are you referring to something else?

If you are referring to tags (and versions in GitHub), the Senzing API server needs to be independently versioned from the Senzing SDK API.   This isn't a foreign concept.  The Senzing API server has many externally declared dependencies in the [pom.xml](https://github.com/Senzing/senzing-api-server/blob/master/pom.xml) file. This is in-line with 12-factor [Dependencies](https://12factor.net/dependencies) thinking.  

We don't version Senzing API server based on the version of any of its dependencies.   And shouldn't, because then the Senzing API server could not put out a [Semantically Versioned](https://semver.org/) feature/fix until the Senzing SDK API did.   That creates monolithic programming which stifles speed of execution.

As @barrycaceres pointed out, the range of acceptable Senzing SDK API version is explicitly declared.   For instance, here's a point-in-time version of the dependencies:  https://github.com/Senzing/senzing-api-server/blob/9d8197517e043c43ea8371e09d173704125325b0/pom.xml#L11-L15.  Since the declaration is in XML, a Git Action could read the `<version>` information during its decision making process, as could any other process.

**Comment by barrycaceres** [comment]
This is not really feasible since the release schedules vary and sometimes we have multiple Senzing API releases for a single API Server release and sometimes it is vice-versa.

**Comment by missulmer** [comment]
Hi there. Product Management here.  We apologize for any inconvenience generated by our differing release cycles between portions in our product stack.  The open-source project releases will remain decoupled from the core engine API and thereby the version numbers will differ.  If that is true, how might we help alleviate your pain?
