### ISSUE TITLE
How to get the match type information on the why results API response

### ISSUE THREAD

**Issue by SaravananKalimuthu21** [Senzing/senzing-api-server#187]
Hi Barry,

We are using the **entities/{entity_id}/why** api to get the why information to show the same exact information of whyresult as like as the below image on our page.

![whyresult1](https://user-images.githubusercontent.com/48215082/92778323-ac672c80-f3be-11ea-994a-4502cf7bbea4.png)

Can we have the match type information like which attribute is a disclosed match and which is a possible match to show in our page?

We can't see such information in the JSON result of the API.

We discussed with Jeff Butcher about this and he said that value was available on the raw JSON and for some reasons you were restricted that in the API response.

Can you add the attribute MATCH LEVEL DESCRIPTION on the API response?

Thanks.

**Comment by SaravananKalimuthu21** [comment]
Hi All,

Checking in..

Thanks.

**Comment by SaravananKalimuthu21** [comment]
Checking in again..

Thanks

**Comment by barrycaceres** [comment]
Adding that should not be a problem.... I will look at doing an API Server revision soon to accommodate this and one other ask I received for the response JSON.

**Comment by SaravananKalimuthu21** [comment]
Thanks a lot, Barry.

**Comment by barrycaceres** [comment]
Turns out that this was an oversight or bug -- it was suppose to be included.  I'm working on it.

**Comment by SaravananKalimuthu21** [comment]
Hi Barry,

Any updates?

**Comment by barrycaceres** [comment]
I have coded the changes and getting ready to release the new version of the API Server with this information.

I am just running the tests today and then will put together the pull request for review and do the release -- it should happen before the end of the week for certain -- possibly today.

**Comment by SaravananKalimuthu21** [comment]
Great to hear this.

It seems you have updated this in senzing api server v2.1.

We are on senzing 1.15. Is that possible for us to access the same feature in our present senzing version 1.15? or should we really need to update our senzing version to 2.x inorder to access the senzing api server v2.1?

Need confirmation.

**Comment by barrycaceres** [comment]
In order to get the fix, it would require an update to version 2.x of Senzing as well as 2.1 of the Senzing API Server.  I can look at doing a 1.x patch, but I would have to get it prioritized with my other work.  I was told by Jeff Butcher that he sent you a note about upgrading last week.  

There are some minor changes in the 2.x API Server that can be seen in the release notes, but should not effect most users and those it does effect should be minor and straightforward to deal with. 

The changes are documented here:

https://github.com/Senzing/senzing-api-server/blob/master/CHANGELOG.md#200---2020-07-16

You can scroll down to the heading "Potentially Backward-Compatibility Breaking Changes by Java class and API Endpoint" to see any changes that might have backward compatibility implications and the migration path.  This is detailed so it looks like there are many, but they are all minor and most deal with "entity classes" and "entity types" configuration which 99% of customers were not using.  Some deal with changes in defaults for query parameters and others deal with query parameter "withRelated" value going from a "true/false" value to an enumerated type of "NONE/PARTIAL/FULL" since there are now three options instead of two.
