### ISSUE TITLE
java runtime is using > 100% CPU on VM

### ISSUE THREAD

**Issue by james-guidehouse** [Senzing/senzing-api-server#204]
The java runtime on the senzing server seems to be using > 100% CPU. I'm not an expert in Linux performance monitoring; I was just using TOP over Putty to see why I was getting 404 errors for valid requests. 

I'm not sure exactly how to reproduce it, but it doesn't seem to be the result of anything we are doing. Just watch the CPU usage for the java runtime -- it should routinely go over 100%. If not, try an API call (/version, for example).

![javaCpu](https://user-images.githubusercontent.com/75760329/101697377-b93eff00-3a45-11eb-8bf0-51a83be5b6ba.png)

**Desktop (please complete the following information):**

- Linux -- not sure which variant
- Putty

**Comment by barrycaceres** [comment]
Something has definitely run afoul there.  You will also notice that it is using nearly 27.9g of resident memory and 66.9g of virtual memory.  We will definitely need more information to try to figure out what is going on.

The Java side itself is likely not the culprit here as it does not hold much in memory at all.  This is probably related to the native libraries being invoked via JNI for the Senzing product -- that part of the product definitely caches things in memory.

So let's get some information:
- What version of Senzing API Server are you using?
- What version of the native Senzing SDK (Senzing product) are you using?
- What database are you using?
- How many records are in your database
- What command-line options were provided to start the API server (specifically of interest is the "concurrency" setting)
- Does this occur after startup or after loading or querying records, and if after some operations are performed, approximately how many before you see this behavior?

**Comment by jamietypovsky** [comment]
Our understanding is that there were issues with your data that caused over-linking.  Please confirm that your issue is resolved and if so, close.  Thank you.  If we don't hear back from you, we will close this item in 7 days.

**Comment by barrycaceres** [comment]
Closing this issue -- please open a new issue if further involvement is needed.
