### ISSUE TITLE
Reduce size of senzing-api-server repository

### ISSUE THREAD

**Issue by docktermj** [Senzing/senzing-api-server#234]
Over time, the size of the `senzing-api-server` repository has become very large.  It take a long while to clone and to use as a submodule.   This issue requests the size of the repository be reduced.

Some ideas on how to do that:

1. https://medium.com/@sangeethkumar.tvm.kpm/cleaning-up-a-git-repo-for-reducing-the-repository-size-d11fa496ba48
2. http://www.obsis.unb.br/gitlab/help/user/project/repository/reducing_the_repo_size_using_git.md
3. https://stackoverflow.com/questions/2116778/reduce-git-repository-size

**Comment by docktermj** [comment]
To see the size, visit https://api.github.com/repos/senzing/senzing-api-server then look for the `size:` property.   The number is in kilobytes.

Reference: https://stackoverflow.com/questions/8646517/how-can-i-see-the-size-of-a-github-repository-before-cloning-it

**Comment by docktermj** [comment]
For reference,

**stream-loader:**  1.5M
**senzing-api-server:**  996M

**Comment by barrycaceres** [comment]
In an effort to reduce the size of the repo we are eradicating the history for the test cache files.  These files can be recreated during the build process and only exist to allow builds on machines where Senzing is not installed or to speed up the build process.

One thing preventing this from working were the old hidden branches associated with pull requests ("hidden refs") which still contained the files to be removed, but were read-only.  Additionally, there are 3 forks:
  -  @sridharkatla at `sridharkatla / senzing-api-server`
  -  @terrorizer1980 at `terrorizer1980 / senzing-api-server`
  -  @timadair at `timadair / rest-api-server-java`
  
In order to remove the files we must detach the forks.  Anybody who has formed may opt to re-fork when the process is complete and this issue is closed.  Please watch this issue for notification that the large files have been removed and the forks have been detached.

**Comment by barrycaceres** [comment]
All forks have been detached and all historical references to the `*Test-cache.zip` files have been removed.  The only remaining are single set for Senzing version 2.8.5 on the current head commit of the repository.

Going forward, only *ONE* version will be checked in new for each new version of `senzing-api-server`.  This will seriously reduce the growth of the repository.  Further, I will investigate the possibility of hosting the test cache externally to the source code and downloading it during the test run instead of making it part of the source code.

Any existing clones should be deleted and re-cloned.

Any existing forks that have been detached can be re-forked.

Closing this issue.

**Comment by barrycaceres** [comment]
This comment servers as a notice to the following if you wish to re-fork:

- @sridharkatla at sridharkatla / senzing-api-server
- @terrorizer1980 at terrorizer1980 / senzing-api-server
- @timadair at timadair / rest-api-server-java
