### ISSUE TITLE
/specifications/open-api missing "version" field

### ISSUE THREAD

**Issue by docktermj** [Senzing/senzing-api-server#237]
Given a Senzing API Server service on "localhost:8250",  when using Swagger,  for example:

```console
docker run \
  --env URL=http://localhost:8250/specifications/open-api \
  --publish 9180:8080 \
  --rm \
  swaggerapi/swagger-ui:v3.23.10
```

Visiting [localhost:9180](http://localhost:9180) gives an error parsing the OpenAPI specification.

**Comment by docktermj** [comment]
Here's what is seen:

![Screenshot from 2021-09-01 18-27-10](https://user-images.githubusercontent.com/9219602/131754244-ea6f0a95-951e-48ba-ba39-7b5f581002df.png)

**Comment by barrycaceres** [comment]
Actually, I think this is caused by failure to provide the `?asRaw=true` query parameter.

If you do not provide that parameter then the Open API specification is contained within the `data` segment of the response which will also have a `meta` and `links` segment.

However, if you specify `?asRaw=true` you should get the open API specification as the root of the JSON document.

**Comment by barrycaceres** [comment]
@docktermj Did adding the `?asRaw=true` fix this?

**Comment by docktermj** [comment]
@barry,   Yes, the following works:

```
docker run \
  --env URL=http://localhost:8250/specifications/open-api?asRaw=true \
  --publish 9180:8080 \
  --rm \
  swaggerapi/swagger-ui:v3.23.10
  ```

Thank you.
